import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import Header from '@/components/Header';

const montrealNormal = localFont({
  variable: '--font-montreal',
  src: '../assets/fonts/ppneuemontreal-book.otf',
});
const montrealMedium = localFont({
  variable: '--font-montrealMedium',
  src: '../assets/fonts/ppneuemontreal-medium.otf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background text-black antialiased pb-12',
          [montrealNormal.className, montrealMedium.className]
        )}
      >
        <div className='pb-custom-28 lg:pb-12 px-6'>
          {' '}
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
